# Generated by Django 4.2.6 on 2023-10-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('legal_number', models.CharField(help_text='CIF/DNI/NIF or other identification number for the invoice customer.', max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('issuer_legal_number', models.CharField(help_text='CIF/DNI/NIF or other identification number for the invoice issuer.', max_length=40)),
                ('concept', models.TextField(help_text='Concept of the invoice. Printed in the pdf.')),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True, help_text='Short description about the invoice for the user. Not printed in the pdf.')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('iban', models.CharField(blank=True, help_text='Optional bank account.', max_length=100)),
                ('irpf', models.PositiveIntegerField(blank=True, default=0, help_text='Retención IRPF (campo opcional).')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.customer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('iva', models.PositiveBigIntegerField(blank=True, default=21)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created'], name='invoices_in_created_dd9d52_idx'),
        ),
    ]
