# Generated by Django 4.2.6 on 2023-11-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_customer_description_customer_phone_customer_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='expire_date',
        ),
    ]
